# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "devopsguys/Windows2012R2Eval"
  
  config.vm.network "forwarded_port", guest: 3389, host: 11580, auto_correct: true
  
  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
  end
  
  config.vm.provision "shell", inline: "& c:\\vagrant\\Configure.ps1"
end
